DROP TABLE IF EXISTS fifa;

CREATE TABLE fifa(
  name TEXT,
  full_name TEXT,
  club TEXT,
  age TEXT,
  league TEXT,
  birth_date TEXT,
  height_cm TEXT,
  weight_kg TEXT,
  nationality TEXT,
  eur_value TEXT,
  eur_wage TEXT,
  eur_release_clause TEXT,
  overall TEXT,
  pac TEXT,
  sho TEXT,
  pas TEXT,
  dri TEXT,
  def TEXT,
  phy TEXT,
  preferred_foot TEXT,
  crossing TEXT,
  finishing TEXT,
  heading_accuracy TEXT,
  short_passing TEXT,
  volleys TEXT,
  dribbling TEXT,
  curve TEXT,
  free_kick_accuracy TEXT,
  long_passing TEXT,
  ball_control TEXT,
  acceleration TEXT,
  sprint_speed TEXT,
  agility TEXT,
  reactions TEXT,
  balance TEXT,
  shot_power TEXT,
  jumping TEXT,
  stamina TEXT,
  strength TEXT,
  long_shots TEXT,
  aggression TEXT
);